# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCEuropeanOptionPricer <- function(optType = "C", Expiry = 0.5, Strike = 100, Spot = 95, Vol = 0.2, r = 0.06, antithetic = FALSE, NumberOfPaths = 1000000L, seed = 0L) {
    .Call(`_OptionPricer_MCEuropeanOptionPricer`, optType, Expiry, Strike, Spot, Vol, r, antithetic, NumberOfPaths, seed)
}

rcpp_hello <- function() {
    .Call(`_OptionPricer_rcpp_hello`)
}

